### ISSUE TITLE
 PR curves and F-measure curves

### ISSUE THREAD

**Issue by WkangLiu** [clelouch/BgNet#2]
Nice work, but I have a question while reading, how did you make your PR curves and F-measure curves, looking forward to your reply!

**Comment by clelouch** [comment]
Thanks for your interest in our work.

Generally, the groundtruth is a binary mask, which assigns 0 to background pixels and 1 to camouflaged pixels. Differently, in the generated prediction maps, the value of a pixel ranges from 0 to 255. We convert them to binary masks by using a threshold ranging from 0 to 255 and calculate the average precision and recall scores of all images in a dataset. Then, a series of average precision and recall scores of the dataset are obtained with threshold sliding from 0 to 255. Based on the precision and recall scores, we plot the PR  and F-measure curves.

**Comment by WkangLiu** [comment]
Thank you for your enthusiastic reply and detailed answer, which code are you referring to generate it?

**Comment by clelouch** [comment]
You can find the evaluation code at https://github.com/DengPingFan/SINet/

**Comment by WkangLiu** [comment]
Oh, Thanks!
